package-lock.json, src/components/common/Button/Button.module.scss, src/components/common/FeatureBox/FeatureBox.module.scss, src/components/common/ProductBox/ProductBox.module.scss, src/components/features/NewFurniture/NewFurniture.module.scss, src/components/features/ProductSearch/ProductSearch.module.scss, src/components/layout/CompanyClaim/CompanyClaim.module.scss, src/components/layout/Footer/Footer.module.scss, src/components/layout/MenuBar/MenuBar.module.scss, src/components/layout/TopBar/TopBar.module.scss, src/styles/settings.scss
Dodałem brakujące zmienne dla kolorów, zgodnie z wytycznymi. Proszę o weryfikację.
=> WDP210801-8

package-lock.json, src/components/common/Button/Button.module.scss, src/components/common/FeatureBox/FeatureBox.module.scss, src/components/common/ProductBox/ProductBox.module.scss, src/components/features/NewFurniture/NewFurniture.module.scss, src/components/features/ProductSearch/ProductSearch.js, src/components/features/ProductSearch/ProductSearch.module.scss, src/components/layout/CompanyClaim/CompanyClaim.module.scss, src/components/layout/Footer/Footer.module.scss, src/components/layout/MenuBar/MenuBar.module.scss, src/components/layout/TopBar/TopBar.module.scss, src/styles/settings.scss
Podmieniłem <select> na dropdown menu stworzone ze struktury  ul>li>ul>li. Unikałem JS'a zgodnie z opisem zadania, więc funkcjonalny jest tylko wygląd menu. Proszę o weryfikację.
=> WDP210801-10

package-lock.json, src/components/common/Button/Button.module.scss, src/components/common/FeatureBox/FeatureBox.js, src/components/common/FeatureBox/FeatureBox.module.scss, src/components/common/ProductBox/ProductBox.module.scss, src/components/features/FeatureBoxes/FeatureBoxes.js, src/components/features/NewFurniture/NewFurniture.module.scss, src/components/features/ProductSearch/ProductSearch.js, src/components/features/ProductSearch/ProductSearch.module.scss, src/components/layout/CompanyClaim/CompanyClaim.module.scss, src/components/layout/Footer/Footer.module.scss, src/components/layout/MenuBar/MenuBar.module.scss, src/components/layout/TopBar/TopBar.module.scss, src/styles/settings.scss
Jeden z komponentów miał na sztywno ustawione efekty, jakie wszystkie komponenty FeatureBox powinny mieć przy hover. Poprawiłem kod i teraz wszystkie te komponenty mają właściwe sachowanie przy hover oraz są linkami kierującymi do adresów wskazanych pod propsem 'href'. Nie było wskazane, dokąd kierować mają linki, więc na ten moment są to '#'. Proszę o weryfikację :)
=> WDP210801-3

src/App.js, src/components/features/NewFurniture/NewFurniture.js, src/components/features/NewFurniture/NewFurnitureContainer.js, src/components/layout/MainLayout/MainLayout.js, src/components/layout/MainLayout/MainLayoutContainer.js, src/redux/MainLayoutRedux.js, src/redux/initialState.js, src/redux/store.js
Dodałem zapisywanie trybu RWD do stanu Aplikacji. W NewFurniture.js dodałem kod, dzięki któremu przy odpowiednim rodzaju RWD komponent renderuje się trochę inaczej. Ze względu na fakt, że pośpieszyłem się z tym zadaniem i nie ma wskazań, jak powinno działać RWD, roboczo dodałem zmiany Desktop = 8 elementów, Tablet = 4 elementy, Phone = 2 elementy. Proszę o weryfikację.
=> WDP210801-20

src/components/common/FeatureBox/FeatureBox.module.scss, src/components/features/FeatureBoxes/FeatureBoxes.js
Dodałem responsywność dla kart korzyści wg polecenia, oraz stylowanie takie żeby karty miały jedną wysokość w rzędzie.
=> WDP210801-16 

src/components/layout/Footer/Footer.js, src/components/layout/Footer/Footer.module.scss
Dodałem responsywność i stylowanie do stopki wg polecenia. Dla telefonów nie było polecenia dla drugiej części stopki, mimo to wycentrowałem elementy tak jak wg mnie wyglądają najlepiej.
=> WDP210801-18

src/components/layout/MenuBar/MenuBar.js, src/components/layout/MenuBar/MenuBar.module.scss
- Dodanie responsywnego layoutu do MenuBar dla trzech opcji: szeroki ekran, tablet, reszta
- Pasek wyszukiwania (komponent: ProductSearch) nadal nie ma responsywnego zachowania (wydaje sie to byc poza zakresem tego zadania)
- Pasek Menu (Home, Furniture itd) ma zaimplementowane trzy lokalizacje: w szeregu z ProductSearch (szeroki ekran), pod ProductSearch (tablet), w guziku menu w szeregu z ProductSearch (reszta)
=> WDP210801-14 Added responsive behaviour to MenuBar

src/App.js, src/components/layout/TopBar/TopBar.js, src/components/views/Login/Login.js, src/components/views/Login/Login.module.scss, src/components/views/Login/Login.test.js, src/styles/settings.scss
Wszystko zrobione według wytycznych, proszę o weryfikację :)
=> WDP210801-41

src/components/features/Feedback/Feedback.js, src/components/features/Feedback/Feedback.module.scss, src/components/features/Feedback/FeedbackContainer.js, src/components/views/Homepage/Homepage.js, src/redux/feedbackRedux.js, src/redux/initialState.js
Dodanie komponentu 'Feedback', jego kontenera oraz styli. Dodatkowo dane pobierane są ze stanu aplikacji.
=> WDP210801-33

src/components/features/OnSpecial/OnSpecial.js, src/components/features/OnSpecial/OnSpecial.module.scss, src/components/features/OnSpecial/OnSpecialContainer.js, src/components/views/Homepage/Homepage.js
- dodałam komponent OnSpecial i jego style 
1. Polecenie mówiło, aby zrobić komponent z promocjami, ale już istniał komponent o nazwie Promotions, stąd mój komponent nazywa się OnSpecial
2. Zdjęcia podane w szablonie nie były dostępne w projekcie, więc ściągnęłam inne z https://www.pexels.com/
- komponent OnSpecial został dodany do Homepage
=> WDP210801-25

src/components/features/NewFurniture/NewFurniture.js, src/components/features/Promotion/Promotion.js, src/components/features/Promotion/Promotion.module.scss
Dodałem RWD dla Promotion oraz funkcje Swipeable do przesuwania slajdów. Druga część nie wiem czy jest poprawnie, dlatego proszę o konstruktywną krytykę.
=> Wdp210801 24

src/components/layout/Brands/Brands.js, src/redux/initialState.js
Zadanie polegało na dodaniu funkcjonalności animacji slidera z markami, tak aby strzałki przesuwały slider o tyle elementów, ile jest widoczne przy danej szerokości ekranu (np. w wersji desktop jest ich 6).
=> WDP210801-31

src/App.js, src/components/layout/TopBar/TopBar.js, src/components/views/Register/Register.js, src/components/views/Register/Register.module.scss, src/styles/settings.scss
Zadanie polegało na stworzeniu podstrony rejestracji zgodnie wizualizacją od klienta. Zadanie nie dotyczyło RWD ani funkcjonalności.
1. Na podstronę przechodzi się klikając przycisk register.
2. Po kliknięciu przycisku WRÓĆ lub ZAREJESTRUJ SIĘ wraca się do strony głównej.
=>  WDP210801-38 

src/components/common/Validation/Validation.js, src/components/views/Login/Login.js, src/components/views/Login/Login.module.scss, src/styles/settings.scss
Wszystko zrobione zgodnie z opisem zadania, proszę o weryfikację :)
=> WDP210801-54

src/components/views/ProductList/ProductList.js, src/components/views/ProductList/ProductList.module.scss
Dodałem baner na wzór zdjęcia z załącznika na ProductList
=> WDP210801-56

src/components/features/NewFurniture/NewFurniture.js
Ujednoliciłem New Furniture. Sekcja nie ulega rozdwojeniu
=> WDP210801-44-NR-2

src/components/features/ProductReviews/ProductReviews.js, src/components/features/ProductReviews/ProductReviews.module.scss, src/components/views/ProductPage/ProductPage.js
Zadanie polegało na stworzeniu modułu pokazującego opinie ludzi na stronie produktu. Ticket nie dotyczy funkcjonalności oraz RWD.
=> WDP210801-49

src/components/features/Feedback/Feedback.js, src/components/features/Feedback/Feedback.module.scss, src/redux/initialState.js
Dodałem Swipeable do przesuwania opinii w Feedback i dodałem trochę stylowania.
=> WDP210801-34

src/components/features/OnSpecial/OnSpecial.js
=> WDP210801-26

src/components/common/BlogBox/BlogBox.js, src/components/common/BlogBox/BlogBox.module.scss, src/components/common/BlogBox/BlogBox.test.js, src/components/views/Blog/Blog.js, src/components/views/Blog/Blog.module.scss, src/components/views/Blog/BlogContainer.js, src/components/views/Homepage/Homepage.js, src/redux/blogRedux.js, src/redux/initialState.js
Wykonałem komponent Blog według wytycznych.  Nie widzę żadnych konfliktów w kodzie. Proszę o weryfikację :)
=> WDP210801-48

css/ProductPage.module.css, src/components/layout/Brands/Brands.module.scss, src/components/views/Register/Register.js, src/components/views/Register/Register.module.scss
Dodałem do formularza dwa inputy: Imię oraz Nazwisko, oraz zrobiłem walidacje formularza według instrukcji.
=> WDP210801-51

src/components/features/NewFurniture/NewFurniture.js, src/components/views/ProductPage/ProductPage.js, yarn.lock
Dodałem NewFurniture do podstrony product, zgodnie z opisem zadania. Dodałem małego Ifa do NewFurniture, dzięki któremu na tej podstronie wyświetla tylko 4 produkty. Proszę o weryfikację :)
=> WDP210801-50

src/components/common/ProductBox/ProductBox.js, src/components/common/ProductBox/ProductBox.module.scss, src/components/features/Popout/Popout.js, src/components/features/Popout/Popout.module.scss
=> Add product popout (WDP210801-46)

src/components/common/CategoryFilter/CategoryFilter.js, src/components/common/CategoryFilter/CategoryFilter.module.scss, src/components/common/CategoryFilter/CategoryFilter.test.js, src/components/common/CategoryFilter/CategoryFilterContainer.js, src/components/views/ProductList/ProductList.js, src/components/views/ProductList/ProductList.module.scss, src/redux/CategoryFilterRedux.js
Wykonałem filtr zgodnie z załącznikiem. Proszę o weryfikację :)
=> WDP210801-63

src/components/views/ProductList/ProductList.js, src/components/views/ProductList/ProductList.module.scss
Zadanie polegało na stworzeniu filtra rozmiarów. Ticket nie dotyczy funkcjonalności ani RWD.
=> WDP210801-66

src/components/common/Button/Button.module.scss, src/components/common/ProductBox/ProductBox.js, src/components/common/ProductBox/ProductBoxContainer.js, src/components/features/CompareProducts/CompareProducts.js, src/components/features/CompareProducts/CompareProducts.module.scss, src/components/features/CompareProducts/CompareProductsContainer.js, src/components/features/NewFurniture/NewFurniture.js, src/components/views/ProductList/ProductList.module.scss, src/redux/compareRedux.js, src/redux/initialState.js, src/redux/store.js
Zadanie polegało na umożliwieniu porównywania produktów. Na dole viewportu dodałam kontener wyświetlający zdjęcia wybranych produktów i przycisk Compare (na ten moment nie ma on dodanej funkcjonalności). Wybrane mogą być maksymalnie cztery produkty. Przy próbie dodania kolejnego wyświetla się komunikat o osiągnięciu limitu.
=> WDP210801-12

src/App.js, src/components/features/BlogPreview/BlogPreview.js, src/components/features/BlogPreview/BlogPreview.module.scss, src/components/features/BlogPreview/BlogPreviewContainer.js, src/components/views/Blog/Blog.js, src/components/views/Blog/Blog.module.scss, src/components/views/Homepage/Homepage.js, src/redux/initialState.js, src/styles/settings.scss
- dodanie podstrony Bloga
- wczesniej istnial folder Blog.js, który odpowiadał za wyświetlanie artykułów z Bloga na stronie głównej. zmieniłam ten komponent na BlogPreview i przerzuciłam go w strukturze projektu pod features
- Podstronę Bloga tworzyłam we wczesniejszym szablonie (w strukturze projektu pod views)
- Polecenie zakładało zrobienie col-9 i col-3 ale przykład klienta bardziej pasował do struktury col-2 / col-7 / col-3
=> Wdp210801 42

src/components/common/ProductBox/ProductBox.js, src/components/features/CompareProducts/CompareProducts.js, src/components/features/CompareProducts/CompareProducts.module.scss
Rozbudowałem Compare o nazwe, cene oraz status bycia ulubionym(bądź jego brak) --> wg polecenia
=> WDP210801-55

src/components/features/NewFurniture/NewFurniture.js, src/components/features/NewFurniture/NewFurniture.module.scss, src/components/views/ProductList/ProductList.js, src/components/views/ProductList/ProductList.module.scss
Zadanie polegało na  dodaniu sekcji new furniture na podstronie shop, tak, by wyświetłała 12 produktów.
=>  WDP210801-58 

src/components/common/ProductsSlider/ProductsSlider.js, src/components/common/ProductsSlider/ProductsSlider.module.scss, src/components/features/Gallery/Gallery.js, src/components/features/Gallery/Gallery.module.scss, src/components/views/ProductList/ProductList.module.scss
Zadanie polegało na stworzeniu wersji mobilnych sekcji Galeria. Na telefonach widoczne są tylko taby ze sliderem, zdjęcie z prawej jest ukryte.
=> WDP210801-29

src/components/layout/CompanyClaim/CompanyClaim.js, src/components/layout/CompanyClaim/CompanyClaim.test.js, src/components/layout/CompanyClaim/CompanyClaimContainer.js, src/components/layout/Header/Header.js
- Dodanie funkcjonalnoci w widgecie koszyka na stronie glownej, gdzie jest pokazywana faktyczna wartosc produktow w koszyku - zgodnie z zadaniem
- po dodaniu kodu nie przechodzily testy, wiec uzupelnilam CompanyClaim.test.js o kod znaleziony na stackoverflow, i sie naprawilo :)
=> WDP210801-60
